apiVersion: apps/v1
kind: Deployment
metadata:
  name: endorser-api-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: endorser-api-1
  template:
    metadata:
      labels:
        app: endorser-api-1
    spec:
      containers:
      - name: endorser-api-1
        image: ghcr.io/nas2020/endorser-api:latest
        ports:
        - containerPort: 5001
        envFrom:
        - configMapRef:
            name: endorser-api-1-config
        - secretRef:
            name: endorser-api-1-secrets